package org.up.ple.workspaces.view;

import org.up.ple.workspaces.WorkspaceSlide;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ExternalResource;
import com.vaadin.server.Resource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;

public class WorkspaceSlideView extends CustomComponent {
			
	private HorizontalLayout horizontalLayout_1;	
	private Link link_1;	
	private Label label_1;
	private WorkspaceSlide slide;

	public WorkspaceSlideView(WorkspaceSlide slide) {
		this.slide = slide;		
		buildMainLayout();
		setCompositionRoot(horizontalLayout_1);		
	}

	
	private void buildMainLayout() {
		horizontalLayout_1 = buildHorizontalLayout_1();						
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);		
		horizontalLayout_1.setMargin(false);
		
		setLabel();						
		setRessource();
//		setName();
		
		return horizontalLayout_1;
	}

	private void setLabel() {
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("40px");
		label_1.setHeight("20px");
		label_1.setValue(slide.getFilterName());				
		horizontalLayout_1.addComponent(label_1);
	}

	private void setRessource() {
		Resource ressource = new ExternalResource(slide.getWebLink());
		// link_1
		link_1 = new Link(slide.getName(), ressource);
		link_1.setWidth("40px");
		link_1.setHeight("20px");
//		link_1.setCaption(slide.get);
		link_1.setImmediate(false);
		horizontalLayout_1.addComponent(link_1);
		
		this.setStyleName(slide.getFilterName()+"_suggested_"+ slide.getMarkupColor());
	}
	
//	private void setName() {
//		Label label = new Label(slide.getName());
//		horizontalLayout_1.addComponent(label);
//	}

}
