package de.unipotsdam.elis.mensa7.layout.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

import de.unipotsdam.elis.mensa7.layout.icons.IconHashMap;
import de.unipotsdam.elis.mensa7.layout.viewmodel.GerichtAdaptor;
import de.unipotsdam.elis.provider.mensa.Gericht;

public class GerichtComposite extends CustomComponent  {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout essenstypContainer;
	@AutoGenerated
	private Button merkenButton;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private Label studentPreis;
	@AutoGenerated
	private Label studentLabel;
	@AutoGenerated
	private Label mitarbeiterPreis;
	@AutoGenerated
	private Label mitarbeiterLabel;
	@AutoGenerated
	private Label gastPreis;
	@AutoGenerated
	private Label gastLabel;
	@AutoGenerated
	private Label beschreibung;
	@AutoGenerated
	private Label titel;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private GerichtAdaptor gerichtAdaptor;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public GerichtComposite(Gericht gericht, IconHashMap iconHashMap) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.gerichtAdaptor = new GerichtAdaptor(studentLabel,studentPreis, mitarbeiterLabel,mitarbeiterPreis,gastLabel,gastPreis,merkenButton,beschreibung,titel,essenstypContainer);
		IconHashMap iconHashMap1 = new IconHashMap();
		gerichtAdaptor.doyourjob(gericht,iconHashMap1);
		
	}

	public GerichtAdaptor getAdaptor() {
		return this.gerichtAdaptor;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("520px");
		mainLayout.setHeight("160px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("520px");
		setHeight("160px");
		
		// titel
		titel = new Label();
		titel.setImmediate(false);
		titel.setWidth("-1px");
		titel.setHeight("-1px");
		titel.setValue("Angebot1");
		mainLayout.addComponent(titel);
		
		// beschreibung
		beschreibung = new Label();
		beschreibung.setImmediate(false);
		beschreibung.setWidth("-1px");
		beschreibung.setHeight("-1px");
		beschreibung.setValue("Gehacktes Elis mit Puderzucker");
		mainLayout.addComponent(beschreibung);
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		mainLayout.addComponent(gridLayout_1);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("200px");
		gridLayout_1.setHeight("-1px");
		gridLayout_1.setMargin(false);
		gridLayout_1.setColumns(2);
		gridLayout_1.setRows(3);
		
		// gastLabel
		gastLabel = new Label();
		gastLabel.setImmediate(false);
		gastLabel.setWidth("-1px");
		gastLabel.setHeight("-1px");
		gastLabel.setValue("Gast");
		gridLayout_1.addComponent(gastLabel, 0, 0);
		
		// gastPreis
		gastPreis = new Label();
		gastPreis.setImmediate(false);
		gastPreis.setWidth("-1px");
		gastPreis.setHeight("-1px");
		gastPreis.setValue("gastPreis");
		gridLayout_1.addComponent(gastPreis, 1, 0);
		
		// mitarbeiterLabel
		mitarbeiterLabel = new Label();
		mitarbeiterLabel.setImmediate(false);
		mitarbeiterLabel.setWidth("-1px");
		mitarbeiterLabel.setHeight("-1px");
		mitarbeiterLabel.setValue("Mitarbeiter");
		gridLayout_1.addComponent(mitarbeiterLabel, 0, 1);
		
		// mitarbeiterPreis
		mitarbeiterPreis = new Label();
		mitarbeiterPreis.setImmediate(false);
		mitarbeiterPreis.setWidth("-1px");
		mitarbeiterPreis.setHeight("-1px");
		mitarbeiterPreis.setValue("mitarbeiterPreis");
		gridLayout_1.addComponent(mitarbeiterPreis, 1, 1);
		
		// studentLabel
		studentLabel = new Label();
		studentLabel.setImmediate(false);
		studentLabel.setWidth("-1px");
		studentLabel.setHeight("-1px");
		studentLabel.setValue("Student");
		gridLayout_1.addComponent(studentLabel, 0, 2);
		
		// studentPreis
		studentPreis = new Label();
		studentPreis.setImmediate(false);
		studentPreis.setWidth("-1px");
		studentPreis.setHeight("-1px");
		studentPreis.setValue("studentPreis");
		gridLayout_1.addComponent(studentPreis, 1, 2);
		
		return gridLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("500px");
		horizontalLayout_1.setHeight("52px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// merkenButton
		merkenButton = new Button();
		merkenButton.setCaption("merken");
		merkenButton.setImmediate(true);
		merkenButton.setWidth("-1px");
		merkenButton.setHeight("-1px");
		horizontalLayout_1.addComponent(merkenButton);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		horizontalLayout_1.addComponent(horizontalLayout_2);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		
		// panel_1
		panel_1 = buildPanel_1();
		horizontalLayout_2.addComponent(panel_1);
		horizontalLayout_2.setComponentAlignment(panel_1, new Alignment(48));
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setWidth("-1px");
		panel_1.setHeight("-1px");
		
		// essenstypContainer
		essenstypContainer = new VerticalLayout();
		essenstypContainer.setImmediate(false);
		essenstypContainer.setWidth("118px");
		essenstypContainer.setHeight("52px");
		essenstypContainer.setMargin(false);
		panel_1.setContent(essenstypContainer);
		
		return panel_1;
	}

}
