package de.unipotsdam.elis.mensa7.layout.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.VerticalLayout;

import de.unipotsdam.elis.mensa7.layout.viewmodel.SpeiseplanAdaptor;

public class SpeiseplanComposite extends CustomComponent  {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout speisePlanContainer;
	@AutoGenerated
	private HorizontalLayout horizontalDateContainer;
	@AutoGenerated
	private Button backButton;
	@AutoGenerated
	private Button nextDay;
	@AutoGenerated
	private PopupDateField dateChooser;



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	private SpeiseplanAdaptor speisePlanAdator;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 5231772332071123298L;
	
	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SpeiseplanComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		//hooking the adaptor
		this.setSpeisePlanAdator(new SpeiseplanAdaptor(dateChooser,nextDay,backButton,speisePlanContainer, horizontalDateContainer));								
//		getAdaptor().doyourjob(speiseplan, new TruncatedDate());
	}



	private void setSpeisePlanAdator(SpeiseplanAdaptor speisePlanAdator) {
		this.speisePlanAdator = speisePlanAdator;
	}



	public SpeiseplanAdaptor getAdaptor() {
		return this.speisePlanAdator;
	}



	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("520px");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("520px");
		setHeight("100.0%");
		
		// horizontalDateContainer
		horizontalDateContainer = buildHorizontalDateContainer();
		mainLayout.addComponent(horizontalDateContainer);
		
		// speisePlanContainer
		speisePlanContainer = new VerticalLayout();
		speisePlanContainer.setStyleName("speiseplan_content");
		speisePlanContainer.setImmediate(false);
		speisePlanContainer.setWidth("-1px");
		speisePlanContainer.setHeight("-1px");
		speisePlanContainer.setMargin(true);
		mainLayout.addComponent(speisePlanContainer);
		mainLayout.setExpandRatio(speisePlanContainer, 1.0f);
		
		return mainLayout;
	}



	@AutoGenerated
	private HorizontalLayout buildHorizontalDateContainer() {
		// common part: create layout
		horizontalDateContainer = new HorizontalLayout();
		horizontalDateContainer.setImmediate(false);
		horizontalDateContainer.setWidth("400px");
		horizontalDateContainer.setHeight("30px");
		horizontalDateContainer.setMargin(false);
		
		// dateChooser
		dateChooser = new PopupDateField();
		dateChooser.setImmediate(false);
		dateChooser.setWidth("-1px");
		dateChooser.setHeight("-1px");
		dateChooser.setInvalidAllowed(false);
		horizontalDateContainer.addComponent(dateChooser);
		
		// nextDay
		nextDay = new Button();
		nextDay.setCaption("morgen");
		nextDay.setImmediate(true);
		nextDay.setWidth("-1px");
		nextDay.setHeight("-1px");
		horizontalDateContainer.addComponent(nextDay);
		
		// backButton
		backButton = new Button();
		backButton.setCaption("gestern");
		backButton.setImmediate(true);
		backButton.setWidth("-1px");
		backButton.setHeight("-1px");
		horizontalDateContainer.addComponent(backButton);
		
		return horizontalDateContainer;
	}

	

}
