package de.unipotsdam.elis.workspacegrid.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.LayoutEvents.LayoutClickEvent;
import com.vaadin.event.LayoutEvents.LayoutClickListener;
import com.vaadin.server.ExternalResource;
import com.vaadin.server.Resource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;

import de.unipotsdam.elis.workspacegrid.model.WorkspaceSlide;

public class WorkspaceSlideView extends CustomComponent {
			
	private HorizontalLayout horizontalLayout_1;			
	private WorkspaceSlide slide;
	private Label label_2;

	public WorkspaceSlideView(WorkspaceSlide slide) {
		this.slide = slide;		
		buildMainLayout();
		setCompositionRoot(horizontalLayout_1);		
	}

	
	private void buildMainLayout() {
		horizontalLayout_1 = buildHorizontalLayout_1();						
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);		
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSizeFull();
		
		setName();
		setRessource();
		setActivities();
		
		
		this.setStyleName(slide.getFilterName());
		
		return horizontalLayout_1;
	}

	private void setName() {
		Label label = new Label(slide.getName());
		horizontalLayout_1.addComponent(label);
	}


	private void setActivities() {
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("40px");
		label_2.setHeight("20px");
		label_2.setValue(slide.getNumberOfNewActivities()+"");				
		horizontalLayout_1.addComponent(label_2);
	}




	private void setRessource() {		
		LayoutClickListener listener = new LayoutClickListener() {
			
			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			@Override
			public void layoutClick(LayoutClickEvent event) {
				getUI().getPage().open(slide.getWebLink().toString(), "_self");				
			}
		};
		horizontalLayout_1.addLayoutClickListener(listener );
		
	}
	

}
